### ISSUE TITLE
When COPY BigQuery table to parquet : Unsupported Arrow type: decimal128

### ISSUE THREAD

**Issue by Jbcot** [hafenkran/duckdb-bigquery#54]
Hello,

I encounter the following issue : 
INTERNAL Error: Unsupported Arrow type: decimal128

when I try to use DuckDB to export a bigquery table into a parquet file stored in a GCS bucket.

Environment : 
Linux system on Google Cloud Shell
DuckDB 1.1.3 used in CLI

-mdh-corporate-sbx1)$ cd
user_name@cloudshell:~ (<myProject>)$ ./duckdb
D INSTALL bigquery FROM community;
D LOAD bigquery;
D ATTACH 'project=myProject' AS bq (TYPE bigquery, READ_ONLY);
D describe bq.myDataset.myTable;
┌─────────────┬───────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │  column_type  │  null   │   key   │ default │  extra  │
│   varchar   │    varchar    │ varchar │ varchar │ varchar │ varchar │
├─────────────┼───────────────┼─────────┼─────────┼─────────┼─────────┤
│ COL1      │ VARCHAR       │ YES     │         │         │         │
│ COL2      │ DECIMAL(29,9) │ YES     │         │         │         │
│ COL3      │ DECIMAL(29,9) │ YES     │         │         │         │
│ COL4      │ DECIMAL(29,9) │ YES     │         │         │         │
│ COL5      │ VARCHAR       │ YES     │         │         │         │
│ COL6      │ VARCHAR       │ YES     │         │         │         │
│ COL7      │ VARCHAR       │ YES     │         │         │         │
│ COL8      │ DECIMAL(29,9) │ YES     │         │         │         │
└─────────────┴───────────────┴─────────┴─────────┴─────────┴─────────┘
D     COPY (
          SELECT *
          FROM bq.myDataset.myTable
      )
      TO 'gs://myBucket/myFile.parquet' (FORMAT PARQUET);
INTERNAL Error: Unsupported Arrow type: decimal128
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors

Thank you in advance !

**Comment by hafenkran** [comment]
Hey @Jbcot 

many thanks for creating this issue!

I have to admit that the NUMERIC/BIGNUMERIC types in DuckDB were a bit neglected, and I overlooked their support in some areas. Other numeric types work seamlessly, but NUMERIC and BIGNUMERIC are not 100% compatible with DuckDB. The max/min scale and precision do not match. 

This PR addresses those gaps and I also introduced some fixes. It improves the handling of parameterized NUMERIC types (precision and scale) and ensures unsupported cases are gracefully skipped instead of triggering internal errors. However, your case of reading NUMERIC values from BigQuery into DuckDB DECIMAL should now work as expected! Once this PR is merged and the master build passes, feel free to pull the fix from my repository.

I’ll plan a community release in the next few days to ensure everyone benefits from this fix.

Cheers!
