### ISSUE TITLE
Add support of execution project selection on ATTACH

### ISSUE THREAD

**Issue by Kayrnt** [hafenkran/duckdb-bigquery#9]
Right now, attaching a GCP project would result in using the project resources (and rights) to execute related queries.
Adding a way to attach the GCP project along an "execution project".

It can be provided this way:
```
ATTACH 'project=my_gcp_bq_storage_project' AS bq (TYPE bigquery, EXECUTION_PROJECT 'my_gcp_bq_execution_project');
```

**Comment by hafenkran** [comment]
Yep, that's a good point and indeed something that’s still pending. Particularly for reading public datasets, I believe this feature is quite important. However, instead of specifying it in the `attach_options`, I prefer to see this in the DSN for consistency reasons, e.g.,

`ATTACH 'my_bq_project.my_dataset exec_project=my_exec_project'  TYPE (bigquery);`

**Comment by Kayrnt** [comment]
Sure I don't mind both 👍
